[package]
name = "tower-def"
version = "0.1.0"
authors = ["Robert Bartlensky"]
edition = "2018"

[dependencies]
amethyst = "0.15.0"
tiled = "0.9.2"
rand = "0.7.3"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
